#!/bin/bash

#[qiaoliyong@oc6105682006 example]$ cat /home/qiaoliyong/sda/iso/fsm/ibm-release
#RHEV-H Blue
#DISTRIBUTIONID = "RHEV-H Blue for ITME"
#CODENAME = "SDMC"
#EXPLOITER = "DirectorAppliance"
#VERSION = "3.0.7"
#PATCHLEVEL = 0
#ibm-release test build for igord

VERSION=$(grep -n '^VERSION' /home/qiaoliyong/sda/iso/fsm/ibm-release | \
          awk -F '=' '{print $2}' | \
          sed -e 's/\"//g' -e 's/[[:space:]]//g')

VERSION=$(sed -n '/^VERSION/p' /home/qiaoliyong/sda/iso/fsm/ibm-release | \
          awk -F '=' '{gsub(/[[:space:]]/,"",$2);gsub(/"/,"",$2); print $2}')
